name: Build and test

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prepare
        run: |
          npm install
          npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx angular-cli-ghpages --base-href=/website/ --repo=https://github.com/ASA-UoA/website.git;
